# -------- Stage 1: Builder --------
FROM python:3.10-slim AS builder

WORKDIR /app

# Install dependencies separately
COPY requirements.txt .
RUN pip install --no-cache-dir --prefix=/install -r requirements.txt


# -------- Stage 2: Final Image --------
FROM python:3.10-slim

WORKDIR /app

# Copy only installed dependencies from builder
COPY --from=builder /install /usr/local

# Copy application code
COPY . .

# Expose port
EXPOSE 5000

# Run app
CMD ["python", "app.py"]